import { Job } from "./types";

const now = Date.now();
const hours = (h: number) => new Date(now - h * 60 * 60 * 1000).toISOString();
const days = (d: number) => new Date(now - d * 24 * 60 * 60 * 1000).toISOString();

// Company logos via Google's favicon API (reliable, free, high-res)
const logo = (domain: string) => `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

export const SAMPLE_JOBS: Job[] = [
  // today
  {
    id: "sample_001",
    title: "senior product manager",
    company: "gitlab",
    companyLogo: logo("gitlab.com"),
    category: "product",
    url: "https://boards.greenhouse.io/gitlab/jobs/7764327002",
    source: "greenhouse",
    tags: ["saas", "devtools"],
    salary: "$130k – $175k",
    postedAt: hours(3),
    scrapedAt: hours(1),
    description: "lead product strategy for the ci/cd platform used by millions of developers worldwide.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_002",
    title: "staff backend engineer",
    company: "zapier",
    companyLogo: logo("zapier.com"),
    category: "engineering",
    url: "https://boards.greenhouse.io/zapier/jobs/5889103",
    source: "greenhouse",
    tags: ["python", "golang"],
    salary: "$140k – $200k",
    postedAt: hours(5),
    scrapedAt: hours(1),
    description: "build scalable automation infrastructure. fully remote since 2011, team across 40+ countries.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_003",
    title: "product designer",
    company: "buffer",
    companyLogo: logo("buffer.com"),
    category: "design",
    url: "https://boards.greenhouse.io/buffer/jobs/4405253006",
    source: "greenhouse",
    tags: ["figma", "design-systems"],
    salary: "$110k – $140k",
    postedAt: hours(8),
    scrapedAt: hours(1),
    description: "design social media tools for 75,000+ customers. async-first, 85+ teammates across 50+ countries.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_004",
    title: "frontend engineer",
    company: "doist",
    companyLogo: logo("doist.com"),
    category: "engineering",
    url: "https://boards.greenhouse.io/doist/jobs/5283146",
    source: "greenhouse",
    tags: ["typescript", "react"],
    salary: "$100k – $140k",
    postedAt: hours(12),
    scrapedAt: hours(1),
    description: "build todoist and twist. no meetings culture, deep work focus, team across 35+ countries.",
    isWorldwide: true,
    employmentType: "full-time",
  },

  // yesterday
  {
    id: "sample_005",
    title: "head of product",
    company: "automattic",
    companyLogo: logo("automattic.com"),
    category: "product",
    url: "https://jobs.lever.co/automattic/8ef0ab0a-7e1e-4c15-8580-19b2c2e3e14a",
    source: "lever",
    tags: ["wordpress", "leadership"],
    salary: "$160k – $200k",
    postedAt: days(1),
    scrapedAt: days(1),
    description: "lead product for wordpress.com. 1,900+ employees in 96 countries, remote-first since founding.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_006",
    title: "senior ux researcher",
    company: "hotjar",
    companyLogo: logo("hotjar.com"),
    category: "design",
    url: "https://boards.greenhouse.io/hotjar/jobs/6040329",
    source: "greenhouse",
    tags: ["user-research"],
    salary: "$90k – $130k",
    postedAt: days(1),
    scrapedAt: days(1),
    description: "research how 1m+ websites use behavior analytics. distributed team across 33 countries.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_007",
    title: "devops engineer",
    company: "grafana labs",
    companyLogo: logo("grafana.com"),
    category: "engineering",
    url: "https://boards.greenhouse.io/grafanalabs/jobs/5896734",
    source: "greenhouse",
    tags: ["kubernetes", "terraform"],
    salary: "$130k – $170k",
    postedAt: days(1),
    scrapedAt: days(1),
    description: "scale infrastructure behind grafana, loki, and tempo. open-source, fully remote.",
    isWorldwide: true,
    employmentType: "full-time",
  },

  // this week
  {
    id: "sample_008",
    title: "product manager — growth",
    company: "deel",
    companyLogo: logo("deel.com"),
    category: "product",
    url: "https://jobs.ashbyhq.com/deel/a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    source: "ashby",
    tags: ["fintech", "global-payroll"],
    salary: "$140k – $180k",
    postedAt: days(3),
    scrapedAt: days(2),
    description: "drive growth for the leading global payroll platform. 4,000+ employees in 150+ countries.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_009",
    title: "senior brand designer",
    company: "toggl",
    companyLogo: logo("toggl.com"),
    category: "design",
    url: "https://jobs.lever.co/toggl/f234a567-89bc-def0-1234-56789abcdef0",
    source: "lever",
    tags: ["branding", "illustration"],
    postedAt: days(4),
    scrapedAt: days(3),
    description: "shape the visual identity of time-tracking tools used by 5m+ people. team across 40 countries.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_010",
    title: "mobile engineer — ios",
    company: "duckduckgo",
    companyLogo: logo("duckduckgo.com"),
    category: "engineering",
    url: "https://boards.greenhouse.io/duckduckgo/jobs/6156781",
    source: "greenhouse",
    tags: ["swift", "ios", "privacy"],
    salary: "$120k – $170k",
    postedAt: days(5),
    scrapedAt: days(4),
    description: "build privacy-first search tools. 200+ employees, fully remote since founding.",
    isWorldwide: true,
    employmentType: "full-time",
  },

  // older (still active)
  {
    id: "sample_011",
    title: "platform engineer",
    company: "canonical",
    companyLogo: logo("canonical.com"),
    category: "engineering",
    url: "https://boards.greenhouse.io/canonical/jobs/5883342",
    source: "greenhouse",
    tags: ["linux", "ubuntu", "golang"],
    salary: "$100k – $150k",
    postedAt: days(10),
    scrapedAt: days(8),
    description: "maintain ubuntu and build cloud infrastructure. distributed team across 40+ countries.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_012",
    title: "product designer",
    company: "maze",
    companyLogo: logo("maze.co"),
    category: "design",
    url: "https://boards.greenhouse.io/maze/jobs/5671234",
    source: "greenhouse",
    tags: ["product-design", "user-testing"],
    postedAt: days(12),
    scrapedAt: days(10),
    description: "design research and testing tools for product teams. remote-first company.",
    isWorldwide: true,
    employmentType: "full-time",
  },

  // expired (14+ days — grayed out)
  {
    id: "sample_013",
    title: "vp of engineering",
    company: "remote",
    companyLogo: logo("remote.com"),
    category: "engineering",
    url: "https://boards.greenhouse.io/remotecom/jobs/5543210",
    source: "greenhouse",
    tags: ["leadership", "hr-tech"],
    postedAt: days(16),
    scrapedAt: days(15),
    description: "lead engineering for a global hr platform.",
    isWorldwide: true,
    employmentType: "full-time",
    expired: true,
  },
  {
    id: "sample_014",
    title: "senior product manager",
    company: "mailerlite",
    companyLogo: logo("mailerlite.com"),
    category: "product",
    url: "https://jobs.lever.co/mailerlite/b789c012-3456-def7-8901-23456789abcd",
    source: "lever",
    tags: ["email-marketing"],
    postedAt: days(18),
    scrapedAt: days(16),
    description: "lead product for email marketing tools. team across 30+ countries.",
    isWorldwide: true,
    employmentType: "full-time",
    expired: true,
  },
];
