import { Job } from "./types";

const now = Date.now();
const hours = (h: number) => new Date(now - h * 60 * 60 * 1000).toISOString();
const days = (d: number) => new Date(now - d * 24 * 60 * 60 * 1000).toISOString();

// Company logos via Google's favicon API (reliable, free, high-res)
const logo = (domain: string) => `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

export const SAMPLE_JOBS: Job[] = [
  {
    id: "sample_001",
    title: "senior frontend engineer",
    company: "linear",
    companyLogo: logo("linear.app"),
    category: "engineering",
    url: "https://jobs.ashbyhq.com/linear",
    source: "ashby",
    tags: ["typescript", "react"],
    salary: "$130k – $180k",
    postedAt: hours(4),
    scrapedAt: hours(1),
    description: "build the fastest project management tool. small, focused team. fully remote worldwide.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_002",
    title: "product designer",
    company: "vercel",
    companyLogo: logo("vercel.com"),
    category: "design",
    url: "https://boards.greenhouse.io/vercel",
    source: "greenhouse",
    tags: ["figma", "design-systems"],
    salary: "$140k – $200k",
    postedAt: hours(9),
    scrapedAt: hours(1),
    description: "shape the future of web development. design for next.js, v0, and the vercel platform.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_003",
    title: "staff backend engineer",
    company: "notion",
    companyLogo: logo("notion.so"),
    category: "engineering",
    url: "https://boards.greenhouse.io/notion",
    source: "greenhouse",
    tags: ["rust", "golang", "distributed-systems"],
    salary: "$180k – $250k",
    postedAt: days(1),
    scrapedAt: hours(6),
    description: "scale the workspace for millions of teams. work on real-time collaboration and data infrastructure.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_004",
    title: "product manager — platform",
    company: "supabase",
    companyLogo: logo("supabase.com"),
    category: "product",
    url: "https://boards.greenhouse.io/supabase",
    source: "greenhouse",
    tags: ["open-source", "developer-tools"],
    salary: "$150k – $190k",
    postedAt: days(2),
    scrapedAt: days(1),
    description: "own the developer experience for the open-source firebase alternative. remote across all timezones.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_005",
    title: "senior product designer",
    company: "gitlab",
    companyLogo: logo("gitlab.com"),
    category: "design",
    url: "https://boards.greenhouse.io/gitlab",
    source: "greenhouse",
    tags: ["ux", "devops"],
    salary: "$120k – $160k",
    postedAt: days(4),
    scrapedAt: days(3),
    description: "design ci/cd workflows for millions of developers. all-remote since 2014, team in 65+ countries.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_006",
    title: "fullstack engineer — ai",
    company: "anthropic",
    companyLogo: logo("anthropic.com"),
    category: "engineering",
    url: "https://boards.greenhouse.io/anthropic",
    source: "greenhouse",
    tags: ["python", "typescript", "llm"],
    salary: "$200k – $300k",
    postedAt: days(6),
    scrapedAt: days(5),
    description: "build tools for safe AI. work on claude and research infrastructure.",
    isWorldwide: true,
    employmentType: "full-time",
  },
  {
    id: "sample_007",
    title: "head of product",
    company: "liveblocks",
    companyLogo: logo("liveblocks.io"),
    category: "product",
    url: "https://jobs.ashbyhq.com/liveblocks",
    source: "ashby",
    tags: ["real-time", "collaboration"],
    salary: "$160k – $210k",
    postedAt: days(8),
    scrapedAt: days(7),
    description: "lead product for real-time collaboration infrastructure. small team, distributed worldwide.",
    isWorldwide: true,
    employmentType: "full-time",
  },
];
